# Generated by Django 4.2.8 on 2024-12-10 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songId', to='tunaapi.genre'),
        ),
        migrations.AlterField(
            model_name='songgenre',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genreId', to='tunaapi.song'),
        ),
    ]
